In [120]:
!pip install pandas openpyxl requests pillow

Requirement already satisfied: pandas in /Users/dianavasileva/Documents/42/Workshops/OpenFoodFacts/open_food_facts_import_module/.venv/lib/python3.12/site-packages (3.0.6)
Requirement already satisfied: openpyxl in /Users/dianavasileva/Documents/42/Workshops/OpenFoodFacts/open_food_facts_import_module/.venv/lib/python3.12/site-packages (3.1.5)
Collecting requests
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting pillow
  Downloading pillow-12.3.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (9.1 kB)
Requirement already satisfied: numpy>=1.26.0 in /Users/dianavasileva/Documents/42/Workshops/OpenFoodFacts/open_food_facts_import_module/.venv/lib/python3.12/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/dianavasileva/Documents/42/Workshops/OpenFoodFacts/open_food_facts_import_module/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: et-xmlfile in /Users/dianavasileva/Documents/42/Workshops/OpenFoodFacts/open_food_facts_import_module/.venv/lib/python3.12/site-packages (from openpyxl) (2.0.0)
Collecting charset_normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.5.2-cp312-cp312-macosx_10_13_universal2.whl.metadata (46 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.20-py3-none-any.whl.metadata (7.2 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Downloading urllib3-2.8.0-py3-none-any.whl.metadata (7.4 kB)
Collecting certifi>=2023.5.7 (from requests)
  Downloading certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: six>=1.5 in /Users/dianavasileva/Documents/42/Workshops/OpenFoodFacts/open_food_facts_import_module/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Downloading charset_normalizer-3.5.2-cp312-cp312-macosx_10_13_universal2.whl (367 kB)
Downloading idna-3.20-py3-none-any.whl (69 kB)
Downloading urllib3-2.8.0-py3-none-any.whl (135 kB)
Downloading pillow-12.3.0-cp312-cp312-macosx_11_0_arm64.whl (4.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 6.9 MB/s  0:00:00 eta 0:00:01m
Downloading certifi-2026.7.22-py3-none-any.whl (136 kB)
Installing collected packages: urllib3, pillow, idna, charset_normalizer, certifi, requests
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6/6 [requests]2/6 [idna]w]
Successfully installed certifi-2026.7.22 charset_normalizer-3.5.2 idna-3.20 pillow-12.3.0 requests-2.34.2 urllib3-2.8.0

In [5]:
import pandas as pd

In [ ]:
excel_file = "../dev_data_struct/sample_salsify.xlsx"

all_sheets = {
    sheet_name: pd.read_excel(excel_file, sheet_name=sheet_name, header=5)
    for sheet_name in pd.ExcelFile(excel_file).sheet_names
}


def clean_sheet_name(sheet_name: str) -> str:
    return sheet_name.split(" - ", 1)[1].replace(", ", "_").replace("  ", " ").replace(" ", "_").replace("&", "").replace("__", "_") if " - " in sheet_name else sheet_name


salsify = {
    clean_sheet_name(sheet_name): df
    for sheet_name, df in all_sheets.items()
}

df = salsify

# Access a sheet directly:
# df["Audio_TV_Computer_Photo"]

In [10]:
print(list(df.keys()))

['Artikelidentifikation', 'Artikelbeschreibung', 'Artikeleigenschaften', 'Artikelmaße', 'Artikelverpackung', 'Artikellogistik', 'Artikelentsorgung', 'Artikelregulierung', 'Produktgruppeninformationen', 'Audio_TV_Computer_Photo', 'Angaben_für_die_Lebensmitt', 'Gefahrgut_Gefahrstoff', 'Angaben_für_die_Gesundheit', 'Kundenspezifische_Attribut', 'German_Austria_Community', 'Mc_Donalds_Attributes', 'BÄKO_Nord_Extension', 'FSC_Attributes', 'Publikation_System-_Sta', 'Components', 'Publishing', '__secret__']

In [36]:
df['Artikellogistik'][['GlobalTradeItemNumber','link']]

,GlobalTradeItemNumber,link
0,GTIN der Artikeleinheit,Datei: URI (Uniform Resource Identifier)
1,Die Global Trade Item Number (GTIN) ist der GS...,"Einfache Zeichenkette, die sich auf eine Inter..."
2,Teil des GDSN Primärschlüssels GLN+GTIN+Zielma...,NaN
3,Muss,Optional
4,GDSN_GlobalTradeItemNumber[14 CHAR],WSCE_DES_WebPageLink[2500 CHAR]
...,...,...
1285,04104420260016,https://mediaservice.alnatura.de/asset/5013243...
1286,04104420261488,https://mediaservice.alnatura.de/asset/5013243...
1287,04104420261365,https://mediaservice.alnatura.de/asset/5013243...
1288,04104420261327,https://mediaservice.alnatura.de/asset/5013243...
1289,00000042328674,https://mediaservice.alnatura.de/asset/5013243...

In [33]:
df["Angaben_für_die_Gesundheit"].columns

Index(['Unnamed: 0', 'GlobalTradeItemNumber', 'InformationProvider',
       'TargetMarketCountryCode', 'HRICompulsoryAdditivesLabelInformation[de]',
       'HRISunProtectionFactor', 'HCIIsTradeItemConsideredGeneric',
       'HCIDoesSaleOfTradeItemRequireGovernmentalReporting',
       'HRIDoesTradeItemContainLatex',
       'HCIDoesTradeItemContainHumanBloodDerivative',
       'HCIDoesTradeItemContainHumanTissue',
       'HCDoesTradeItemContainAnimalTissue', 'prescriptionTypeCode',
       'PIIIsTradeItemBeMarkedNoShake', 'drugSideEffectsAndWarningsValue[de]',
       'drugInteractionsValue[de]', 'dosageFormTypeCodeReferenceValue',
       'dosageFormTypeCodeDescription', 'dosageFormTypeCodeListName',
       'dosageFormTypeCodeListURI', 'dosageFormTypeCodeListVersion',
       'dosageFormTypeCodeListAgencyCode', 'dosageFormTypeCodeListAgencyName',
       'dosageFormTypeCodeListAgencyCodeListVersion',
       'dosageRecommendationValue[de]', 'dosageRestrictionLimitsValue[de]',
       'MDIsTradeItemImplantable', 'MDIsTradeItemExemptFromDirectPartMarking',
       'MDIIsExemptFromPremarketAuthorisation', 'MDIsActiveDevice',
       'MDHasDeviceMeasuringFunction',
       'MDIsDeviceIntendedToAdministerOrRemoveMedicinalProduct',
       'MDIsDeviceMedicinalProduct', 'MDIsDeviceExemptFromImplantObligations',
       'MDIsReprocessedSingleUseDevice', 'MDIsReusableSurgicalInstrument',
       'MDMaximumCyclesReusable', 'MDMRICompatibility',
       'MDManufacturerDeclaredReusabilityType',
       'initialManufacturerSterilisationCode',
       'initialSterilisationPriorToUseCode',
       'MDIIsTradeItemRequiredToRemainSterile', 'MDIUdidDeviceCount',
       'directPartMarkingIdentifierValue', 'identificationSchemeName',
       'identificationSchemeAgencyCode', 'identificationSchemeAgencyName',
       'identificationSchemeAgencyCodeCodeListVersion',
       'uDIProductionIdentifierTypeCodeValue',
       'annexXVIIntendedPurposeTypeCodeValue', 'globalModelNumber',
       'globalModelDescription[de]', 'contactTypeCode', 'personName',
       'departmentName', 'jobTitle', 'responsibility[de]',
       'communicationChannelCode', 'communicationValue',
       'communicationChannelName', 'isCommunicationChannelPreferred',
       'afterHoursCommunicationChannelCode', 'afterHoursCommunicationValue',
       'afterHoursCommunicationChannelName',
       'afterHoursIsCommunicationChannelPreferred', 'globalModelRegulatoryAct',
       'countryCode', 'countrySubdivisionCodeValue',
       'MDTIMMedicalDeviceSoftwareCode', 'HPWIsPackagingMarkedWithIngredients',
       'packagingMarkedNutritionLabelCodeValue', 'gtin', 'DUNSNumber',
       'DUNSPlus4Number', 'fDAPreferredTermCode', 'gMDNPreferredTermCode',
       'fDAPremarketSubmissionNumber', 'productCode',
       'fDAMedicalDeviceListing', 'DonationIdentificationNumberMarked'],
      dtype='str')

In [30]:
df["Angaben_für_die_Gesundheit"][['GlobalTradeItemNumber',
                                'HRICompulsoryAdditivesLabelInformation[de]']]

,GlobalTradeItemNumber,HRICompulsoryAdditivesLabelInformation[de]
0,GTIN der Artikeleinheit,Zusätzliche verpflichtende Kennzeichnung und W...
1,Die Global Trade Item Number (GTIN) ist der GS...,Hier werden gesetzlich vorgeschriebene Informa...
2,Teil des GDSN Primärschlüssels GLN+GTIN+Zielma...,NaN
3,Muss,Optional
4,GDSN_GlobalTradeItemNumber[14 CHAR],GDSN_CompulsoryAdditivesLabelInformation[5000 ...
...,...,...
1285,04104420260016,Unter Schutzatmosphäre verpackt.
1286,04104420261488,NaN
1287,04104420261365,NaN
1288,04104420261327,NaN
1289,00000042328674,NaN

In [28]:
df["Gefahrgut_Gefahrstoff"][['GlobalTradeItemNumber',
                            'WSCEDangerousGoodsIndication']]

,GlobalTradeItemNumber,WSCEDangerousGoodsIndication
0,GTIN der Artikeleinheit,Gefahrgut
1,Die Global Trade Item Number (GTIN) ist der GS...,"Angabe, ob der Artikel und/oder mindestens ein..."
2,Teil des GDSN Primärschlüssels GLN+GTIN+Zielma...,NaN
3,Muss,Optional
4,GDSN_GlobalTradeItemNumber[14 CHAR],WSCE_DangerousGoodsIndication[200 CHAR]
...,...,...
1285,04104420260016,ZNA
1286,04104420261488,ZNA
1287,04104420261365,ZNA
1288,04104420261327,ZNA
1289,00000042328674,ZNA

In [27]:
df["Angaben_für_die_Lebensmitt"][['GlobalTradeItemNumber',
                           'ingredientStatementValue[de]',
                           'FBSNumberOfServingsPerPackage',
                           'wSCEDietTypeCode',
                           'allergenTypeCode',
                           'nutritionalValueReference',
                           'nutritionalValueReferenceUOM',
                           'servingSizeValue',
                           'servingSizeValueUOM',
                           'calorificValueKcal',
                           'calorificValueKJ',
                           'nutritionalContent',
                           'nutritionalContentQuantityContainedValue',
                           'nutritionalContentQuantityContainedUOM',
                           'nutritionalContent.1',
                           'nutritionalContentQuantityContainedValue.1',
                           'nutritionalContentQuantityContainedUOM.1',
                           'nutritionalContent.2',
                           'nutritionalContentQuantityContainedValue.2',
                           'nutritionalContentQuantityContainedUOM.2',
                           'nutritionalContent.3',
                           'nutritionalContentQuantityContainedValue.3',
                           'nutritionalContentQuantityContainedUOM.3',
                           'nutritionalContent.4',
                           'nutritionalContentQuantityContainedValue.4',
                           'nutritionalContentQuantityContainedUOM.4',
                           'nutritionalContent.5',
                           'nutritionalContentQuantityContainedValue.5',
                           'nutritionalContentQuantityContainedUOM.5',
                           'nutritionalContent.6',
                           'nutritionalContentQuantityContainedValue.6',
                           'nutritionalContentQuantityContainedUOM.6',
                           'nutritionalContent.7',
                           'nutritionalContentQuantityContainedValue.7',
                           'nutritionalContentQuantityContainedUOM.7',
                           'nutritionalContent.8',
                           'nutritionalContentQuantityContainedValue.8',
                           'nutritionalContentQuantityContainedUOM.8',
                        #    'vitaminMineralCode',
                        #    'vitaminMineralValue',
                        #    'vitaminMineralValueUnitOfMeasure',
                           'nutritionalValueReference',
                           'nutritionalValueReferenceUOM',
                           'servingSizeValue',
                           'servingSizeValueUOM',
                           'calorificValueKcal',
                           'calorificValueKJ'
                           ]]

,GlobalTradeItemNumber,ingredientStatementValue[de],FBSNumberOfServingsPerPackage,wSCEDietTypeCode,allergenTypeCode,nutritionalValueReference,nutritionalValueReferenceUOM,servingSizeValue,servingSizeValueUOM,calorificValueKcal,...,nutritionalContentQuantityContainedUOM.7,nutritionalContent.8,nutritionalContentQuantityContainedValue.8,nutritionalContentQuantityContainedUOM.8,nutritionalValueReference,nutritionalValueReferenceUOM,servingSizeValue,servingSizeValueUOM,calorificValueKcal,calorificValueKJ
0,GTIN der Artikeleinheit,Zutatenliste,Anzahl der Portionen pro Packung,Ernährungshinweise: Ernährungsart,Allergen: Code,Nährwertkennzeichnung: Bezugsgröße,Nährwertkennzeichnung Bezugsgröße: Maßeinheit,Portionsgröße: Wert,Portionsgröße: Maßeinheit,Energie [kcal],...,Nährwertangaben: Wert Maßeinheit,Nährwertangaben: Bestandteil,Nährwertangaben: Wert,Nährwertangaben: Wert Maßeinheit,Nährwertkennzeichnung: Bezugsgröße,Nährwertkennzeichnung Bezugsgröße: Maßeinheit,Portionsgröße: Wert,Portionsgröße: Maßeinheit,Energie [kcal],Energie [kJ]
1,Die Global Trade Item Number (GTIN) ist der GS...,Auflistung der wesentlichen im Artikel enthalt...,"Die Gesamtzahl an Portionen, die in der Packun...","Angabe der Ernährungsweise, für die der Artike...","Code, der die Art des Allergens angibt.","Angabe der Portionsgröße, auf die sich die Ang...",Maßeinheit der Angabe der Portionsgröße auf di...,"Angabe der Portionsgröße, auf die sich die Ang...",Maßeinheit der Portionsgröße.,Energiewert in Kilokalorien (kcal) bezogen auf...,...,Messwert des Nährstoffes oder Nährwertbestandt...,"Ein Code, der einen im Produkt enthaltenen Näh...",Messwert des Nährstoffes oder Nährwertbestandt...,Messwert des Nährstoffes oder Nährwertbestandt...,"Angabe der Portionsgröße, auf die sich die Ang...",Maßeinheit der Angabe der Portionsgröße auf di...,"Angabe der Portionsgröße, auf die sich die Ang...",Maßeinheit der Portionsgröße.,Energiewert in Kilokalorien (kcal) bezogen auf...,Energiewert in Kilojoule (kJ) bezogen auf die ...
2,Teil des GDSN Primärschlüssels GLN+GTIN+Zielma...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Muss,Optional,Optional,Optional,Optional,Optional,Optional,Optional,Optional,Optional,...,Optional,Optional,Optional,Optional,Optional,Optional,Optional,Optional,Optional,Optional
4,GDSN_GlobalTradeItemNumber[14 CHAR],GDSN_DES_IngredientStatement[5000 CHAR],GDSN_NumberOfServingsPerPackage[31 CHAR],WSCE_DES_DietTypeCode[200 CHAR],WSCE_DES_AllergenTypeCode[200 CHAR],WSCE_DES_NutritionalValueReference[16 CHAR],WSCE_DES_NutritionalValueReferenceUOM[200 CHAR],WSCE_DES_ServingSizeValue[10 CHAR],WSCE_DES_ServingSizeValueUOM[200 CHAR],WSCE_DES_CalorificValueKcal[16 CHAR],...,WSCE_DES_NutritionalContentValueUOM[200 CHAR],WSCE_DES_NutritionalContent[200 CHAR],WSCE_DES_NutritionalContentValue[16 CHAR],WSCE_DES_NutritionalContentValueUOM[200 CHAR],WSCE_DES_NutritionalValueReference[16 CHAR],WSCE_DES_NutritionalValueReferenceUOM[200 CHAR],WSCE_DES_ServingSizeValue[10 CHAR],WSCE_DES_ServingSizeValueUOM[200 CHAR],WSCE_DES_CalorificValueKcal[16 CHAR],WSCE_DES_CalorificValueKJ[16 CHAR]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1285,04104420260016,"Zutaten: Hirse*, Meersalz *aus biologischer La...",NaN,VEGAN,AN,100,GRM,NaN,NaN,384,...,NaN,NaN,NaN,NaN,100,GRM,NaN,NaN,384,1627
1286,04104420261488,"Zutaten: WEIZENSIRUP* 38 %, WEIZENMEHL*, Palmö...",NaN,VEGETARIAN,AM,100,GRM,NaN,NaN,449,...,NaN,NaN,NaN,NaN,100,GRM,NaN,NaN,449,1884
1287,04104420261365,"Zutaten: Ingwer* 50 %, Pfefferminze* 35 %, Kra...",NaN,VEGAN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1288,04104420261327,"Zutaten: Kamille* 39 %, Fenchel* 31 %, Pfeffer...",NaN,VEGAN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1289,00000042328674,"Zutaten: MILCH* pasteurisiert, Speisesalz, mik...",NaN,VEGETARIAN,AM,100,GRM,NaN,NaN,251,...,NaN,NaN,NaN,NaN,100,GRM,NaN,NaN,251,1043

In [21]:
df["Artikelverpackung"][['GlobalTradeItemNumber',
                           'IsPackagingMarkedReturnable']]

,GlobalTradeItemNumber,IsPackagingMarkedReturnable
3,Muss,Muss
4,GDSN_GlobalTradeItemNumber[14 CHAR],GDSN_IsPackagingMarkedReturnable[200 CHAR]
5,04104420073685,false
6,04104420083325,false
7,04104420031081,false
...,...,...
1285,04104420260016,false
1286,04104420261488,false
1287,04104420261365,false
1288,04104420261327,false
1289,00000042328674,false

In [19]:
df["Artikelmaße"][['GlobalTradeItemNumber',
                           'NetWeight',
                           'NetWeightUOM',
                           'GrossWeightValue',
                           'GrossWeightUOM']]

,GlobalTradeItemNumber,NetWeight,NetWeightUOM,GrossWeightValue,GrossWeightUOM
3,Muss,Optional,Bedingt muss,Optional,Bedingt muss
4,GDSN_GlobalTradeItemNumber[14 CHAR],GDSN_Measurements_NetWeight[31 CHAR],GDSN_Measurements_NetWeightUOM[200 CHAR],GDSN_Measurements_GrossWeight[31 CHAR],GDSN_Measurements_GrossWeightUOM[200 CHAR]
5,04104420073685,125,GRM,126,GRM
6,04104420083325,125,GRM,218,GRM
7,04104420031081,340,GRM,522,GRM
...,...,...,...,...,...
1285,04104420260016,75,GRM,80,GRM
1286,04104420261488,175,GRM,182.91,GRM
1287,04104420261365,30,GRM,65.06,GRM
1288,04104420261327,30,GRM,66.98,GRM
1289,00000042328674,300,GRM,305,GRM

In [16]:
df["Artikelbeschreibung"][['GlobalTradeItemNumber',
                           'TIDFunctionalName[de]',
                           'TIDDescriptionShort[de]',
                           'TIDBrandName',
                           'regulatedProductNameValue[de]']]

,GlobalTradeItemNumber,TIDFunctionalName[de],TIDDescriptionShort[de],TIDBrandName,regulatedProductNameValue[de]
3,Muss,Muss,Optional,Muss,NaN
4,GDSN_GlobalTradeItemNumber[14 CHAR],GDSN_FunctionalName[35 CHAR],GDSN_DescriptionShort[40 CHAR],GDSN_BrandName[70 CHAR],GDSN_DES_RegulatedProductName[500 CHAR]
5,04104420073685,Weichkäse,Hessischer Handkäse Minis 125G,Alnatura,Bio Sauermilchkäse
6,04104420083325,Obst,Birne pur 125G,Alnatura,Bio Birnenmark
7,04104420031081,Tomatensoßen,Tomatensauce Toscana 325ML,Alnatura,Bio Tomatensauce mit Gemüse
...,...,...,...,...,...
1285,04104420260016,sonstige Chips/Flips,Hirsebällchen 75G,Alnatura,"Bio Hirse-Knabbergebäck, extrudiert"
1286,04104420261488,Waffeln,Honigwaffeln 175G,Alnatura,Bio Waffeln gefüllt mit Sirup und Honig
1287,04104420261365,Kräutertee im Beutel,"Ingwer Minze Tee Btl. 20x1,5g 30G",Alnatura,Bio Kräuterteemischung mit Ingwer
1288,04104420261327,Kräutertee im Beutel,"Kräuter Lavendel Tee Btl. 20x1,5g 30G",Alnatura,Bio Kräuterteemischung aromatisiert mit Lavend...
1289,00000042328674,anderer Käse,Mozzarella Rolle 300g,Alnatura,"Bio Mozzarella, mindestens 45% Fett i. Tr."

In [13]:
df["Artikelidentifikation"][['GlobalTradeItemNumber',
                             'NameOfBrandOwner',
                             'targetMarketCountryCode']]

,GlobalTradeItemNumber,NameOfBrandOwner,targetMarketCountryCode
3,Muss,Bedingt optional,Muss
4,GDSN_GlobalTradeItemNumber[14 CHAR],GDSN_NameOfBrandOwner[200 CHAR],GDSN_DES_ContactInformationTargetMarketCountry...
5,04104420073685,Alnatura GmbH,NaN
6,04104420083325,Alnatura GmbH,NaN
7,04104420031081,Alnatura GmbH,NaN
...,...,...,...
1285,04104420260016,Alnatura GmbH,NaN
1286,04104420261488,Alnatura GmbH,NaN
1287,04104420261365,Alnatura GmbH,NaN
1288,04104420261327,Alnatura GmbH,NaN
1289,00000042328674,Alnatura GmbH,NaN

In [37]:
from functools import reduce

# Merge all dataframes on GlobalTradeItemNumber
dfs_to_merge = [
    df["Angaben_für_die_Gesundheit"][['GlobalTradeItemNumber',
                                'HRICompulsoryAdditivesLabelInformation[de]']],
    df["Gefahrgut_Gefahrstoff"][['GlobalTradeItemNumber',
                            'WSCEDangerousGoodsIndication']],
    df['Artikellogistik'][['GlobalTradeItemNumber','link']],
    df["Angaben_für_die_Lebensmitt"][['GlobalTradeItemNumber',
                           'ingredientStatementValue[de]',
                           'FBSNumberOfServingsPerPackage',
                           'wSCEDietTypeCode',
                           'allergenTypeCode',
                           'nutritionalValueReference',
                           'nutritionalValueReferenceUOM',
                           'servingSizeValue',
                           'servingSizeValueUOM',
                           'calorificValueKcal',
                           'calorificValueKJ',
                           'nutritionalContent',
                           'nutritionalContentQuantityContainedValue',
                           'nutritionalContentQuantityContainedUOM',
                           'nutritionalContent.1',
                           'nutritionalContentQuantityContainedValue.1',
                           'nutritionalContentQuantityContainedUOM.1',
                           'nutritionalContent.2',
                           'nutritionalContentQuantityContainedValue.2',
                           'nutritionalContentQuantityContainedUOM.2',
                           'nutritionalContent.3',
                           'nutritionalContentQuantityContainedValue.3',
                           'nutritionalContentQuantityContainedUOM.3',
                           'nutritionalContent.4',
                           'nutritionalContentQuantityContainedValue.4',
                           'nutritionalContentQuantityContainedUOM.4',
                           'nutritionalContent.5',
                           'nutritionalContentQuantityContainedValue.5',
                           'nutritionalContentQuantityContainedUOM.5',
                           'nutritionalContent.6',
                           'nutritionalContentQuantityContainedValue.6',
                           'nutritionalContentQuantityContainedUOM.6',
                           'nutritionalContent.7',
                           'nutritionalContentQuantityContainedValue.7',
                           'nutritionalContentQuantityContainedUOM.7',
                           'nutritionalContent.8',
                           'nutritionalContentQuantityContainedValue.8',
                           'nutritionalContentQuantityContainedUOM.8']],
    df["Artikelverpackung"][['GlobalTradeItemNumber',
                           'IsPackagingMarkedReturnable']],
    df["Artikelmaße"][['GlobalTradeItemNumber',
                           'NetWeight',
                           'NetWeightUOM',
                           'GrossWeightValue',
                           'GrossWeightUOM']],
    df["Artikelbeschreibung"][['GlobalTradeItemNumber',
                           'TIDFunctionalName[de]',
                           'TIDDescriptionShort[de]',
                           'TIDBrandName',
                           'regulatedProductNameValue[de]']],
    df["Artikelidentifikation"][['GlobalTradeItemNumber',
                             'NameOfBrandOwner',
                             'targetMarketCountryCode']]
]

# Merge all dataframes on GlobalTradeItemNumber
merged_df = reduce(lambda left, right: left.merge(right, on='GlobalTradeItemNumber', how='outer'), dfs_to_merge)

merged_df

,GlobalTradeItemNumber,HRICompulsoryAdditivesLabelInformation[de],WSCEDangerousGoodsIndication,link,ingredientStatementValue[de],FBSNumberOfServingsPerPackage,wSCEDietTypeCode,allergenTypeCode,nutritionalValueReference,nutritionalValueReferenceUOM,...,NetWeight,NetWeightUOM,GrossWeightValue,GrossWeightUOM,TIDFunctionalName[de],TIDDescriptionShort[de],TIDBrandName,regulatedProductNameValue[de],NameOfBrandOwner,targetMarketCountryCode
0,00000040045009,NaN,ZNA,https://mediaservice.alnatura.de/asset/5013243...,Zutaten: Vollmilchschokolade* 50 % (Rohrohrzuc...,1,VEGETARIAN,AM,100,GRM,...,37.5,GRM,39,GRM,Schokoriegel,"Café Biscuit Schokoriegel 37,5G",Alnatura,Bio Vollmilchschokolade mit Espresso- Milchcre...,Alnatura GmbH,NaN
1,00000040045016,"; Kakaoanteil 32,00% mindestens in der Schokolade",ZNA,https://mediaservice.alnatura.de/asset/5013243...,Zutaten: Vollmilchschokolade* 50 % (Rohrohrzuc...,1,VEGETARIAN,AM,100,GRM,...,37.5,GRM,39,GRM,Schokoriegel,"Himbeer Joghurt Schokoriegel 37,5G",Alnatura,Bio Vollmilchschokolade mit Himbeer- Joghurt-F...,Alnatura GmbH,NaN
2,00000040045030,"Kakaoanteil 40,00 % mindestens in der Schokolade",ZNA,https://mediaservice.alnatura.de/asset/5013243...,"Zutaten: Rohrohrzucker*, Kakaobutter*, VOLLMIL...",NaN,VEGETARIAN,AM,100,GRM,...,15,GRM,17,GRM,Weihn. Zwidu süß,*Winter VM Schoko Lolli 15G*,Alnatura,Bio Vollmilchschokolade am Stiel,Alnatura GmbH,NaN
3,00000040045047,NaN,ZNA,https://mediaservice.alnatura.de/asset/5013243...,"Zutaten: Anis*, Fenchel*, Koriander*, Kümmel* ...",NaN,VEGAN,BC,100,GRM,...,8,GRM,10,GRM,Gewürz/Kräutermisch,Brotgewürz 8G,Alnatura,"Bio Brotgewürz, gemahlen",Alnatura GmbH,NaN
4,00000040045078,NaN,ZNA,https://mediaservice.alnatura.de/asset/5013243...,"Zutaten: ROGGENVOLLKORNMEHL*, Starterkulturen ...",NaN,VEGAN,AW,100,GRM,...,15,GRM,17,GRM,Backtriebmittel,Sauerteig Extrakt 15G,Alnatura,Bio Sauerteigextrakt,Alnatura GmbH,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1285,Die Global Trade Item Number (GTIN) ist der GS...,Hier werden gesetzlich vorgeschriebene Informa...,"Angabe, ob der Artikel und/oder mindestens ein...","Einfache Zeichenkette, die sich auf eine Inter...",Auflistung der wesentlichen im Artikel enthalt...,"Die Gesamtzahl an Portionen, die in der Packun...","Angabe der Ernährungsweise, für die der Artike...","Code, der die Art des Allergens angibt.","Angabe der Portionsgröße, auf die sich die Ang...",Maßeinheit der Angabe der Portionsgröße auf di...,...,Das Nettogewicht meint das Gewicht des Artikel...,Maßeinheit des Nettogewichts des Artikels (z.B...,Das Bruttogewicht enthält auch das Gewicht des...,Maßeinheit des Bruttogewichts des Artikels (z....,Die Funktionsbezeichnung beschreibt den regulä...,"Artikelkurzbezeichnung, d.h. kurze, möglichst ...","Der Name, mit dem der Inhaber der Marke sein P...","Rechtlich vorgeschriebene Produktbezeichnung, ...","Name der Partei (Firma, natürliche Person, o.ä...","Der Zielmarkt, der mit den angegebenen Kommuni..."
1286,GDSN_GlobalTradeItemNumber[14 CHAR],GDSN_CompulsoryAdditivesLabelInformation[5000 ...,WSCE_DangerousGoodsIndication[200 CHAR],WSCE_DES_WebPageLink[2500 CHAR],GDSN_DES_IngredientStatement[5000 CHAR],GDSN_NumberOfServingsPerPackage[31 CHAR],WSCE_DES_DietTypeCode[200 CHAR],WSCE_DES_AllergenTypeCode[200 CHAR],WSCE_DES_NutritionalValueReference[16 CHAR],WSCE_DES_NutritionalValueReferenceUOM[200 CHAR],...,GDSN_Measurements_NetWeight[31 CHAR],GDSN_Measurements_NetWeightUOM[200 CHAR],GDSN_Measurements_GrossWeight[31 CHAR],GDSN_Measurements_GrossWeightUOM[200 CHAR],GDSN_FunctionalName[35 CHAR],GDSN_DescriptionShort[40 CHAR],GDSN_BrandName[70 CHAR],GDSN_DES_RegulatedProductName[500 CHAR],GDSN_NameOfBrandOwner[200 CHAR],GDSN_DES_ContactInformationTargetMarketCountry...
1287,GTIN der Artikeleinheit,Zusätzliche verpflichtende Kennzeichnung und W...,Gefahrgut,Datei: URI (Uniform Resource Identifier),Zutatenliste,Anzahl der Portionen pro Packung,Ernährungshinweise: Ernährungsart,Allergen: Code,Nährwertkennzeichnung: Bezugsgröße,Nährwertkennzeichnung Bezugsgröße: Maßeinheit,...,Nettogewicht,Nettogewicht: Maßeinheit,Bruttogewicht,Bruttogewicht: Maßeinheit,Funktionsbezeichnung,Artikelkurzbezeichnung,Markenname,Rechtlich vorgeschriebene Produktbezeichnung,Markeninhaber: Name,Zielmarkt: Ländercode (Kontakt)
1288,Muss,Optional,Optional,Optional,Optional,Optional,Optional,Optional,Optional,Optional,...,Optional,Bedingt muss,Optional,Bedingt muss,Muss,Optional,Muss,NaN,Bedingt optional,Muss
1289,Teil des GDSN Primärschlüssels GLN+GTIN+Zielma...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,"Mussangabe, wenn Orderable Unit = true",NaN,NaN,NaN,NaN,NaN,NaN,Teil des GDSN Primärschlüssels (GLN+GTIN+Zielm...

In [32]:
df_output = pd.read_csv("../loader_output.csv")
df_output

,code,HRICompulsoryAdditivesLabelInformation[de],WSCEDangerousGoodsIndication,ingredients,FBSNumberOfServingsPerPackage,branded_food_category,allergenTypeCode,nutritionalValueReference,nutritionalValueReferenceUOM,serving_size,...,package_weight,NetWeightUOM,GrossWeightValue,GrossWeightUOM,TIDFunctionalName[de],short_description,brands,regulatedProductNameValue[de],brand_owner,market_country
0,00000040045009,NaN,ZNA,Zutaten: Vollmilchschokolade* 50 % (Rohrohrzuc...,1,VEGETARIAN,AM,100,GRM,NaN,...,37.5,GRM,39,GRM,Schokoriegel,"Café Biscuit Schokoriegel 37,5G",Alnatura,Bio Vollmilchschokolade mit Espresso- Milchcre...,Alnatura GmbH,NaN
1,00000040045016,"; Kakaoanteil 32,00% mindestens in der Schokolade",ZNA,Zutaten: Vollmilchschokolade* 50 % (Rohrohrzuc...,1,VEGETARIAN,AM,100,GRM,NaN,...,37.5,GRM,39,GRM,Schokoriegel,"Himbeer Joghurt Schokoriegel 37,5G",Alnatura,Bio Vollmilchschokolade mit Himbeer- Joghurt-F...,Alnatura GmbH,NaN
2,00000040045030,"Kakaoanteil 40,00 % mindestens in der Schokolade",ZNA,"Zutaten: Rohrohrzucker*, Kakaobutter*, VOLLMIL...",NaN,VEGETARIAN,AM,100,GRM,NaN,...,15,GRM,17,GRM,Weihn. Zwidu süß,*Winter VM Schoko Lolli 15G*,Alnatura,Bio Vollmilchschokolade am Stiel,Alnatura GmbH,NaN
3,00000040045047,NaN,ZNA,"Zutaten: Anis*, Fenchel*, Koriander*, Kümmel* ...",NaN,VEGAN,BC,100,GRM,NaN,...,8,GRM,10,GRM,Gewürz/Kräutermisch,Brotgewürz 8G,Alnatura,"Bio Brotgewürz, gemahlen",Alnatura GmbH,NaN
4,00000040045078,NaN,ZNA,"Zutaten: ROGGENVOLLKORNMEHL*, Starterkulturen ...",NaN,VEGAN,AW,100,GRM,NaN,...,15,GRM,17,GRM,Backtriebmittel,Sauerteig Extrakt 15G,Alnatura,Bio Sauerteigextrakt,Alnatura GmbH,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1285,Die Global Trade Item Number (GTIN) ist der GS...,Hier werden gesetzlich vorgeschriebene Informa...,"Angabe, ob der Artikel und/oder mindestens ein...",Auflistung der wesentlichen im Artikel enthalt...,"Die Gesamtzahl an Portionen, die in der Packun...","Angabe der Ernährungsweise, für die der Artike...","Code, der die Art des Allergens angibt.","Angabe der Portionsgröße, auf die sich die Ang...",Maßeinheit der Angabe der Portionsgröße auf di...,"Angabe der Portionsgröße, auf die sich die Ang...",...,Das Nettogewicht meint das Gewicht des Artikel...,Maßeinheit des Nettogewichts des Artikels (z.B...,Das Bruttogewicht enthält auch das Gewicht des...,Maßeinheit des Bruttogewichts des Artikels (z....,Die Funktionsbezeichnung beschreibt den regulä...,"Artikelkurzbezeichnung, d.h. kurze, möglichst ...","Der Name, mit dem der Inhaber der Marke sein P...","Rechtlich vorgeschriebene Produktbezeichnung, ...","Name der Partei (Firma, natürliche Person, o.ä...","Der Zielmarkt, der mit den angegebenen Kommuni..."
1286,GDSN_GlobalTradeItemNumber[14 CHAR],GDSN_CompulsoryAdditivesLabelInformation[5000 ...,WSCE_DangerousGoodsIndication[200 CHAR],GDSN_DES_IngredientStatement[5000 CHAR],GDSN_NumberOfServingsPerPackage[31 CHAR],WSCE_DES_DietTypeCode[200 CHAR],WSCE_DES_AllergenTypeCode[200 CHAR],WSCE_DES_NutritionalValueReference[16 CHAR],WSCE_DES_NutritionalValueReferenceUOM[200 CHAR],WSCE_DES_ServingSizeValue[10 CHAR],...,GDSN_Measurements_NetWeight[31 CHAR],GDSN_Measurements_NetWeightUOM[200 CHAR],GDSN_Measurements_GrossWeight[31 CHAR],GDSN_Measurements_GrossWeightUOM[200 CHAR],GDSN_FunctionalName[35 CHAR],GDSN_DescriptionShort[40 CHAR],GDSN_BrandName[70 CHAR],GDSN_DES_RegulatedProductName[500 CHAR],GDSN_NameOfBrandOwner[200 CHAR],GDSN_DES_ContactInformationTargetMarketCountry...
1287,GTIN der Artikeleinheit,Zusätzliche verpflichtende Kennzeichnung und W...,Gefahrgut,Zutatenliste,Anzahl der Portionen pro Packung,Ernährungshinweise: Ernährungsart,Allergen: Code,Nährwertkennzeichnung: Bezugsgröße,Nährwertkennzeichnung Bezugsgröße: Maßeinheit,Portionsgröße: Wert,...,Nettogewicht,Nettogewicht: Maßeinheit,Bruttogewicht,Bruttogewicht: Maßeinheit,Funktionsbezeichnung,Artikelkurzbezeichnung,Markenname,Rechtlich vorgeschriebene Produktbezeichnung,Markeninhaber: Name,Zielmarkt: Ländercode (Kontakt)
1288,Muss,Optional,Optional,Optional,Optional,Optional,Optional,Optional,Optional,Optional,...,Optional,Bedingt muss,Optional,Bedingt muss,Muss,Optional,Muss,NaN,Bedingt optional,Muss
1289,Teil des GDSN Primärschlüssels GLN+GTIN+Zielma...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,"Mussangabe, wenn Orderable Unit = true",NaN,NaN,NaN,NaN,NaN,NaN,Teil des GDSN Primärschlüssels (GLN+GTIN+Zielm...

In [77]:
import json
import warnings
from pathlib import Path
from typing import Dict, List, Optional
import pandas as pd

# Suppress openpyxl warnings about missing default styles
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")


class ColumnNameConverter:
    """Convert and normalize data from Salsify/EDA to database schema using column_mapper.json"""

    GS1_NUTRIENT_CODES = {
        "FAT",
        "FASAT",
        "CHOAVL",
        "SUGAR-",
        "PRO-",
        "FIBTG",
        "SALTEQ",
        "FAMSCIS",
        "FAPUCIS",
    }

    def __init__(self, mapper_path: Optional[str] = None):
        """Initialize the converter with a column mapper file.

        Args:
            mapper_path: Path to column_mapper.json. If None, looks for it in the current directory.
        """
        if mapper_path is None:
            mapper_path = "column_mapper.json"

        self.mapper_path = Path(mapper_path)
        self.db_to_eda_map = self._load_mapper()
        self.eda_to_db_map = self._invert_mapper()

    def _load_mapper(self) -> Dict[str, Optional[str]]:
        """Load the column mapper from JSON file."""
        if not self.mapper_path.exists():
            raise FileNotFoundError(f"Column mapper file not found: {self.mapper_path}")

        with open(self.mapper_path, "r", encoding="utf-8") as f:
            return json.load(f)

    def _invert_mapper(self) -> Dict[Optional[str], str]:
        """Invert the mapper to go from EDA column names to database column names."""
        inverted: Dict[Optional[str], str] = {}
        for db_col, eda_col in self.db_to_eda_map.items():
            if eda_col is not None:
                inverted[eda_col] = db_col
        return inverted

    def _extract_gs1_nutrients(self, df: pd.DataFrame) -> Dict[str, pd.Series]:
        """Dynamically extracts nutrients by scanning GS1 repeating group columns.

        In Salsify exports, nutrients are distributed across repeated columns
        ('nutritionalContent', 'nutritionalContent.1', etc.) instead of fixed indices.
        """
        slots = []
        for i in range(50):
            suffix = "" if i == 0 else f".{i}"
            code_col = f"nutritionalContent{suffix}"
            val_col = f"nutritionalContentQuantityContainedValue{suffix}"
            uom_col = f"nutritionalContentQuantityContainedUOM{suffix}"
            if code_col in df.columns and val_col in df.columns:
                slots.append(
                    (code_col, val_col, uom_col if uom_col in df.columns else None)
                )

        extracted: Dict[str, pd.Series] = {}
        for gs1_code in self.GS1_NUTRIENT_CODES:
            s_val = pd.Series(index=df.index, dtype="float64")
            for code_col, val_col, _ in slots:
                mask = df[code_col] == gs1_code
                if mask.any():
                    numeric_vals = pd.to_numeric(df.loc[mask, val_col], errors="coerce")
                    s_val = s_val.combine_first(numeric_vals)
            extracted[gs1_code] = s_val

        return extracted

    def convert(self, df: pd.DataFrame) -> pd.DataFrame:
        """Convert DataFrame column names and extract nutrients into the database schema.

        Handles:
          1. Direct column mappings without dictionary inversion collisions.
          2. Dynamic GS1 nutrient extraction based on nutrient codes (PRO-, FAT, SALTEQ, etc.).
          3. Units and energy calculation (kcal / kJ).
        """
        result_df = pd.DataFrame(index=df.index)

        # Detect and extract dynamic GS1 nutrients if present
        has_gs1_nutrients = any("nutritionalContent" in col for col in df.columns)
        gs1_nutrients = self._extract_gs1_nutrients(df) if has_gs1_nutrients else {}

        for target_col, source in self.db_to_eda_map.items():
            if source is None:
                continue

            # Case A: Source is a GS1 nutrient code
            if source in self.GS1_NUTRIENT_CODES:
                if source in gs1_nutrients:
                    val_series = gs1_nutrients[source]
                    # Convert salt to sodium if target is sodium:
                    # 1 g salt (SALTEQ) = 0.4 g sodium (400 mg)
                    if "sodium" in target_col.lower() and source == "SALTEQ":
                        if "labelNutrients" in target_col or "mg" in target_col.lower():
                            result_df[target_col] = val_series * 400.0
                        else:
                            result_df[target_col] = val_series / 2.5
                    else:
                        result_df[target_col] = val_series

            # Case B: Source is a direct column present in input DataFrame
            elif source in df.columns:
                result_df[target_col] = df[source]

            # Case C: Source is a static unit string
            elif source in ["g", "kcal", "kJ", "mg", "GRM", "MLT"]:
                result_df[target_col] = source

        # Populate flat nutrient columns if present in target schema or needed
        if "protein_value" not in result_df.columns and "PRO-" in gs1_nutrients:
            result_df["protein_value"] = gs1_nutrients["PRO-"]
            result_df["protein_unit"] = "g"
        if "sugar_value" not in result_df.columns and "SUGAR-" in gs1_nutrients:
            result_df["sugar_value"] = gs1_nutrients["SUGAR-"]
            result_df["sugar_unit"] = "g"
        if "salt_value" not in result_df.columns and "SALTEQ" in gs1_nutrients:
            result_df["salt_value"] = gs1_nutrients["SALTEQ"]
            result_df["salt_unit"] = "g"
        if "saturated_fat_value" not in result_df.columns and "FASAT" in gs1_nutrients:
            result_df["saturated_fat_value"] = gs1_nutrients["FASAT"]
            result_df["saturated_fat_unit"] = "g"
        if (
            "energy_value" not in result_df.columns
            and "calorificValueKcal" in df.columns
        ):
            result_df["energy_value"] = pd.to_numeric(
                df["calorificValueKcal"], errors="coerce"
            )
            result_df["energy_unit"] = "kcal"

        return result_df


    def save_converted_data(
        self, converted_df: pd.DataFrame, output_path: str
    ) -> None:
        """Convert DataFrame and save to file.

        Args:
            converted_df: DataFrame with converted column names
            output_path: Path to save the converted data
        """
        out_path = Path(output_path)
        out_path.parent.mkdir(parents=True, exist_ok=True)

        converted_df.to_csv(out_path, index=False, encoding="utf-8")

        print(f"Converted data saved to: {out_path}")



from functools import reduce

converter = ColumnNameConverter()

print("Loading data from Excel...")
excel_file = (
    "../input/sample_salsify.xlsx"
)

try:
    all_sheets = {
        sheet_name: pd.read_excel(excel_file, sheet_name=sheet_name, header=5)
        for sheet_name in pd.ExcelFile(excel_file).sheet_names
    }

    def clean_sheet_name(sheet_name: str) -> str:
        return (
            sheet_name.split(" - ", 1)[1]
            .replace(", ", "_")
            .replace("  ", " ")
            .replace(" ", "_")
            .replace("&", "")
            .replace("__", "_")
            if " - " in sheet_name
            else sheet_name
        )

    df = {clean_sheet_name(name): s_df for name, s_df in all_sheets.items()}

    nutri_cols = [
        "GlobalTradeItemNumber",
        "ingredientStatementValue[de]",
        "FBSNumberOfServingsPerPackage",
        "wSCEDietTypeCode",
        "allergenTypeCode",
        "nutritionalValueReference",
        "nutritionalValueReferenceUOM",
        "servingSizeValue",
        "servingSizeValueUOM",
        "calorificValueKcal",
        "calorificValueKJ",
    ]
    # Include all nutritionalContent slots present in sheet
    for col in df["Angaben_für_die_Lebensmitt"].columns:
        if col.startswith("nutritionalContent") and col not in nutri_cols:
            nutri_cols.append(col)

    dfs_to_merge = [
        df["Angaben_für_die_Gesundheit"][
            ["GlobalTradeItemNumber", "HRICompulsoryAdditivesLabelInformation[de]"]
        ],
        df["Gefahrgut_Gefahrstoff"][
            ["GlobalTradeItemNumber", "WSCEDangerousGoodsIndication"]
        ],
        df["Artikellogistik"][["GlobalTradeItemNumber", "link"]],
        df["Angaben_für_die_Lebensmitt"][nutri_cols],
        df["Artikelverpackung"][
            ["GlobalTradeItemNumber", "IsPackagingMarkedReturnable"]
        ],
        df["Artikelmaße"][
            [
                "GlobalTradeItemNumber",
                "NetWeight",
                "NetWeightUOM",
                "GrossWeightValue",
                "GrossWeightUOM",
            ]
        ],
        df["Artikelbeschreibung"][
            [
                "GlobalTradeItemNumber",
                "TIDFunctionalName[de]",
                "TIDDescriptionShort[de]",
                "TIDBrandName",
                "regulatedProductNameValue[de]",
            ]
        ],
        df["Artikelidentifikation"][
            ["GlobalTradeItemNumber", "NameOfBrandOwner", "targetMarketCountryCode"]
        ],
    ]

    merged_df = reduce(
        lambda left, right: left.merge(
            right, on="GlobalTradeItemNumber", how="outer"
        ),
        dfs_to_merge,
    )

    converted_df = converter.convert(merged_df)[:100] # TODO

    output_path = "../output/loader_output.csv"
    converter.save_converted_data(converted_df, str(output_path))

except FileNotFoundError as e:
    print(f"Error: {e}")

Loading data from Excel...
Converted data saved to: ../output/loader_output.csv

In [113]:
test_product_name = converted_df.loc[converted_df['code'].apply(lambda x: '4104420259782' in str(x))]
test_product_name['code'] = '19970505'
test_product_name.to_csv("../output/loader_output_test_product_name_himbeere.csv", index=False, encoding="utf-8")
test_product_name.T

                                                                                                 1253
code                                                                                         19970505
brand_owner                                                                             Alnatura GmbH
brands                                                                Fruchteis Himbeere 1 Stk, 46 ml
ingredients                                         Zutaten: Himbeerpüree* 56 %, Traubensaftkonzen...
serving_size                                                                                      NaN
serving_size_unit                                                                                 NaN
branded_food_category                                                                     Kleineis TK
package_weight                                                                                     49
market_country                                                                                    NaN
short_description                                                     Fruchteis Himbeere 1 Stk, 46 ml
labelNutrients.fat.value                                                                          0.5
labelNutrients.saturatedFat.value                                                                 0.1
labelNutrients.sodium.value                                                                       4.0
labelNutrients.carbohydrates.value                                                               18.0
labelNutrients.fiber.value                                                                        2.7
labelNutrients.sugars.value                                                                      18.0
labelNutrients.protein.value                                                                      1.0
labelNutrients.calories.value                                                                      81
foodNutrients.Protein.amount                                                                      1.0
foodNutrients.Protein.nutrient.unitName                                                             g
foodNutrients.Total Sugars.amount                                                                18.0
foodNutrients.Total Sugars.nutrient.unitName                                                        g
foodNutrients.Sodium, Na.amount                                                                 0.004
foodNutrients.Sodium, Na.nutrient.unitName                                                          g
foodNutrients.Fatty acids, total saturated.amount                                                 0.1
foodNutrients.Fatty acids, total saturated.nutr...                                                  g
foodNutrients.Energy.amount                                                                        81
foodNutrients.Energy.nutrient.unitName                                                           kcal
protein_value                                                                                     1.0
protein_unit                                                                                        g
sugar_value                                                                                      18.0
sugar_unit                                                                                          g
salt_value                                                                                       0.01
salt_unit                                                                                           g
saturated_fat_value                                                                               0.1
saturated_fat_unit                                                                                  g
energy_value                                                                                     81.0
energy_unit                                                                                      kcal

In [121]:
df_output = pd.read_csv("../loader_output.csv")
df_output[['code','product_front_image_link']]

               code                           product_front_image_link
0          40045009  https://mediaservice.alnatura.de/asset/5013243...
1          40045016  https://mediaservice.alnatura.de/asset/5013243...
2          40045030  https://mediaservice.alnatura.de/asset/5013243...
3          40045047  https://mediaservice.alnatura.de/asset/5013243...
4          40045078  https://mediaservice.alnatura.de/asset/5013243...
...             ...                                                ...
1280  4260100260056  http://media.alnatura.de/packshots/rest/images...
1281  4260100261633  http://media.alnatura.de/packshots/rest/images...
1282  4260100261916  https://mediaservice.alnatura.de/image/5013243...
1283  4260100263323  https://mediaservice.alnatura.de/image/5013243...
1284  4262366594005                                                NaN

[1285 rows x 2 columns]

In [122]:
import os
import requests
from pathlib import Path
from urllib.parse import urlparse
from PIL import Image
from io import BytesIO

# Create a directory for images
images_dir = Path("../product_images")
images_dir.mkdir(parents=True, exist_ok=True)

# Track download progress
successful = 0
failed = 0
failed_codes = []

# Download images
for idx, row in df_output.iterrows():
    code = str(row['code']).strip()
    image_url = str(row['product_front_image_link']).strip()
    
    # Skip if URL is empty or NaN
    if not image_url or image_url.lower() == 'nan':
        continue
    
    try:
        # Download image
        response = requests.get(image_url, timeout=10)
        response.raise_for_status()
        
        # Convert to JPG and save
        img = Image.open(BytesIO(response.content)).convert('RGB')
        image_path = images_dir / f"{code}.jpg"
        img.save(image_path, 'JPEG', quality=95)
        
        successful += 1
        if (idx + 1) % 50 == 0:
            print(f"Downloaded {idx + 1} images...")
            
    except Exception as e:
        failed += 1
        failed_codes.append(code)
        if failed <= 10:  # Show first 10 errors
            print(f"Failed to download {code}: {str(e)[:100]}")

print(f"\n✓ Successfully downloaded: {successful}")
print(f"✗ Failed: {failed}")
print(f"Images saved to: {images_dir.resolve()}")

Failed to download 40045030: 404 Client Error: Not Found for url: https://mediaservice.alnatura.de/asset/501324310981/image_gjjnr
Failed to download 40045078: 404 Client Error: Not Found for url: https://mediaservice.alnatura.de/asset/501324310981/image_crhrv
Failed to download 40045115: 404 Client Error: Not Found for url: https://mediaservice.alnatura.de/asset/501324310981/image_864pn
Failed to download 40045122: 404 Client Error: Not Found for url: https://mediaservice.alnatura.de/asset/501324310981/image_37r1r
Failed to download 40045177: 404 Client Error: Not Found for url: https://mediaservice.alnatura.de/asset/501324310981/image_7p5av
Failed to download 40045221: 404 Client Error: Not Found for url: https://mediaservice.alnatura.de/asset/501324310981/image_un2uc
Failed to download 40045238: 404 Client Error: Not Found for url: https://mediaservice.alnatura.de/asset/501324310981/image_bs8hh
Failed to download 40045252: 404 Client Error: Not Found for url: https://mediaservice.alnatura.de/asset/501324310981/image_1b7ca
Failed to download 40045283: 404 Client Error: Not Found for url: https://mediaservice.alnatura.de/asset/501324310981/image_flrlk
Failed to download 40045344: 404 Client Error: Not Found for url: https://mediaservice.alnatura.de/asset/501324310981/image_i5mpf
Downloaded 50 images...
Downloaded 100 images...
Downloaded 200 images...
Downloaded 250 images...
Downloaded 300 images...
Downloaded 350 images...
Downloaded 400 images...
Downloaded 450 images...
Downloaded 500 images...
Downloaded 550 images...
Downloaded 600 images...
Downloaded 650 images...
Downloaded 700 images...
Downloaded 750 images...
Downloaded 800 images...
Downloaded 850 images...
Downloaded 900 images...
Downloaded 1050 images...
Downloaded 1100 images...
Downloaded 1150 images...
Downloaded 1250 images...

✓ Successfully downloaded: 807
✗ Failed: 473
Images saved to: /Users/dianavasileva/Documents/42/Workshops/OpenFoodFacts/open_food_facts_import_module/src/product_images